version: '3.7'
services:
  app:
    container_name: 'app'
    build:
      context: ./docker/app
    volumes:
      - .:/go/src/esmini
    ports:
      - 8080:8080
    networks:
      - esnet
  es01:
    container_name: 'es01'
    build: ./docker/elasticsearch
    ports:
      - 9200:9200
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    networks:
      - esnet
  es02:
    container_name: 'es02'
    build: ./docker/elasticsearch
    ports:
      - 9201:9200
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.1
    container_name: 'kibana'
    links:
      - es01:elasticsearch
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
networks:
  esnet:
